"""initial schema

Revision ID: ad9bfda917ac
Revises: 
Create Date: 2026-03-30 21:28:15.432068
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9bfda917ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=True),
    sa.Column('metric', sa.Text(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('search_vector', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_runs_agent_status', 'runs', ['agent_name', 'status'], unique=False)
    op.create_index('idx_runs_alert_eval', 'runs', ['agent_name', 'started_at', 'status'], unique=False)
    op.create_index('idx_runs_started_at', 'runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_runs_agent_name'), 'runs', ['agent_name'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_rule_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('parent_step_id', sa.Uuid(), nullable=True),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('step_type', sa.Text(), nullable=False),
    sa.Column('step_name', sa.Text(), nullable=True),
    sa.Column('input', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('search_vector', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_id')
    )
    op.create_index('idx_events_run_id', 'events', ['run_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_run_id', table_name='events')
    op.drop_table('events')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_runs_agent_name'), table_name='runs')
    op.drop_index('idx_runs_started_at', table_name='runs')
    op.drop_index('idx_runs_alert_eval', table_name='runs')
    op.drop_index('idx_runs_agent_status', table_name='runs')
    op.drop_table('runs')
    op.drop_table('alert_rules')
    op.drop_table('agents')
    # ### end Alembic commands ###
